# Generated by Django 4.2.16 on 2025-05-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_savingproducts_savingoptions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavingOptions",
        ),
        migrations.DeleteModel(
            name="SavingProducts",
        ),
    ]
