# Generated by Django 4.2.16 on 2025-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_depositproducts_savingproducts_savingoptions_and_more"),
        ("accounts", "0004_user_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribed",
        ),
        migrations.AddField(
            model_name="user",
            name="subscirbed_saving_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to="products.savingproducts",
                verbose_name="가입한 적금 상품",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_deposit_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to="products.depositproducts",
                verbose_name="가입한 정기예금 상품",
            ),
        ),
    ]
