# Generated by Django 4.2.16 on 2025-05-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_create_default_user"),
        ("accounts", "0007_fix_typo_subscribed_saving_products"),
    ]

    operations = []
